from question import Question

data = [
    Question(
        "A bat and a ball cost £1.10 in total. The bat costs £1.00 more than the ball. How much does the ball cost?",
        ["5 pence",
         "10 pence",
         "9 pence",
         "1 pence"]),
    Question("If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
             ["5 minutes",
              "100 minutes",
              "20 minutes",
              "500 minute"]),
    Question("In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days for the patch to cover the entire lake, how long would it take for the patch to cover half of the lake?",
             ["47 days",
              "24 days",
              "12 days",
              "36 days"]),
    Question("If John can drink one barrel of water in 6 days, and Mary can drink one barrel of water in 12 days, how long would it take them to drink one barrel of water together ?",
             ["4 days",
              "9 days",
              "12 days",
              "3 days"]),
    Question("Jerry received both the 15th highest and the 15th lowest mark in the class. How many students are in the class ?",
             ["29 students",
              "30 students",
              "1 student",
              "15 students"]),
    Question("A man buys a pig for £60, sells it for £70, buys it back for £80, and sells it finally for £90. How much has he made?",
             ["20 pounds",
              "10 pounds",
              "0 pounds",
              "30 pounds"]),
    Question("Simon decided to invest £8,000 in the stock market one day early in 2008. Six months after he invested, on July 17, the stocks he had purchased were down 50%. Fortunately for Simon, from July 17 to October 17, the stocks he had purchased went up 75%. What is Simon's economic situation at this point ?",
             ["has lost money.",
              "is ahead of where he began.",
              "has broken even in the stock market." 
              ,"it cannot be determined."]),
    ]

data2 = [
    Question("Mary's father has 5 daughters but no sons : Nana,Nene, Nini, Nono. What is the fifth daughter's name probably ?",
             []),
    Question("If you were running a race, and you passed the person in 2nd place, what place would you be in now ?",
             []),
    Question("It is a stormy night and a plane takes off from JFK airport in New York. The storm worsens, and the plane crashes-half lands in the United States, the other half lands in Canada. In which country do you bury the survivors?",
             []),
    Question("A monkey, a squirrel, and a bird are racing to the top of a coconut tree. Who will get the banana first, the monkey, the squirrel, or the bird?",
             []),
    Question("In a one-storey pink house, there was a pink person, a pink cat, a pink fish, a pink computer, a pink chair, a pink table, a pink telephone, a pink shower — everything was pink! What colour were the stairs probably?",
             []),
    Question("How many of each animal did Moses put on the ark ?",
             []),
    Question("The wind blows west. An electric train runs east. In which cardinal direction does the smoke from the locomotive blow ?",
             []),
    Question("If you have only one match and you walk into a darkroom where there is an oil lamp, a newspaper and wood — which thing would you light first?",
             []),
    Question("Would it be ethical for a man to marry the sister of his widow ?",
             []),
    Question("Which sentence is correct: (a) ‘the yolk of the egg are white’ or (b) ‘the yolk of the egg is white’?",
             [])
]
